-- Email classifications: per-email structured classification generated by AI.
-- One row per email, upsert on email_id.

CREATE TABLE email_classifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email_id uuid NOT NULL REFERENCES incoming_emails(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  sender_id uuid NOT NULL REFERENCES email_senders(id) ON DELETE CASCADE,
  email_type text NOT NULL CHECK (email_type IN (
    'welcome', 'promotional', 'newsletter', 'cart_abandon', 'winback',
    'transactional', 'announcement', 'survey', 'loyalty', 'seasonal', 'other'
  )),
  offer text,
  discount_pct smallint CHECK (discount_pct >= 0 AND discount_pct <= 100),
  urgency text NOT NULL DEFAULT 'none' CHECK (urgency IN ('none', 'soft', 'hard')),
  cta text,
  products_mentioned text[] NOT NULL DEFAULT '{}',
  tone text NOT NULL DEFAULT 'casual' CHECK (tone IN ('formal', 'casual', 'urgent', 'friendly', 'luxury')),
  personalization_level text NOT NULL DEFAULT 'none' CHECK (personalization_level IN ('none', 'basic', 'moderate', 'advanced')),
  subject_length smallint,
  subject_has_emoji boolean NOT NULL DEFAULT false,
  subject_has_personalization boolean NOT NULL DEFAULT false,
  subject_urgency_words text[] NOT NULL DEFAULT '{}',
  model text NOT NULL,
  classified_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_email_classifications_email ON email_classifications (email_id);
CREATE INDEX idx_email_classifications_sender ON email_classifications (sender_id, classified_at DESC);

ALTER TABLE email_classifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Members can view email classifications"
  ON email_classifications FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM project_members
      WHERE project_members.project_id = email_classifications.project_id
        AND project_members.user_id = auth.uid()
    )
  );

CREATE POLICY "Owners and editors can manage email classifications"
  ON email_classifications FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM project_members
      WHERE project_members.project_id = email_classifications.project_id
        AND project_members.user_id = auth.uid()
        AND project_members.role IN ('owner', 'editor')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM project_members
      WHERE project_members.project_id = email_classifications.project_id
        AND project_members.user_id = auth.uid()
        AND project_members.role IN ('owner', 'editor')
    )
  );

-- Sender strategies: comprehensive strategy analysis generated by AI.
-- Append-only — new row per regeneration, query latest by generated_at DESC LIMIT 1.

CREATE TABLE sender_strategies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL REFERENCES email_senders(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  strategy jsonb NOT NULL DEFAULT '{}'::jsonb,
  email_count integer NOT NULL DEFAULT 0,
  date_range_start timestamptz,
  date_range_end timestamptz,
  model text NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_sender_strategies_sender ON sender_strategies (sender_id, generated_at DESC);

DROP TRIGGER IF EXISTS set_sender_strategies_updated_at ON sender_strategies;
CREATE TRIGGER set_sender_strategies_updated_at
  BEFORE UPDATE ON sender_strategies
  FOR EACH ROW
  EXECUTE FUNCTION public.touch_updated_at();

ALTER TABLE sender_strategies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Members can view sender strategies"
  ON sender_strategies FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM project_members
      WHERE project_members.project_id = sender_strategies.project_id
        AND project_members.user_id = auth.uid()
    )
  );

CREATE POLICY "Owners and editors can manage sender strategies"
  ON sender_strategies FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM project_members
      WHERE project_members.project_id = sender_strategies.project_id
        AND project_members.user_id = auth.uid()
        AND project_members.role IN ('owner', 'editor')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM project_members
      WHERE project_members.project_id = sender_strategies.project_id
        AND project_members.user_id = auth.uid()
        AND project_members.role IN ('owner', 'editor')
    )
  );

-- RPC: list unclassified emails for a sender (by domains)
CREATE OR REPLACE FUNCTION list_unclassified_sender_emails(
  p_project_id uuid,
  p_sender_id uuid,
  p_limit integer DEFAULT 500
)
RETURNS TABLE (
  id uuid,
  subject text,
  body_text text,
  from_address text,
  created_at timestamptz
)
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT ie.id, ie.subject, ie.body_text, ie.from_address, ie.created_at
  FROM incoming_emails ie
  INNER JOIN email_domains ed ON ed.domain = ie.from_domain AND ed.project_id = ie.project_id
  LEFT JOIN email_classifications ec ON ec.email_id = ie.id
  WHERE ie.project_id = p_project_id
    AND ed.sender_id = p_sender_id
    AND ie.deleted_at IS NULL
    AND ec.id IS NULL
  ORDER BY ie.created_at DESC
  LIMIT p_limit;
$$;
