-- Sender profiles: structured company analysis generated by AI.
-- Append-only — new row per regeneration, query latest by generated_at DESC LIMIT 1.

CREATE TABLE sender_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL REFERENCES email_senders(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_urls text[] NOT NULL DEFAULT '{}',
  model text NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_sender_profiles_sender_generated
  ON sender_profiles (sender_id, generated_at DESC);
CREATE INDEX idx_sender_profiles_project
  ON sender_profiles (project_id);

-- Trigger for updated_at
DROP TRIGGER IF EXISTS set_sender_profiles_updated_at ON sender_profiles;
CREATE TRIGGER set_sender_profiles_updated_at
  BEFORE UPDATE ON sender_profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.touch_updated_at();

-- RLS
ALTER TABLE sender_profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Members can view sender profiles"
  ON sender_profiles FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM project_members
      WHERE project_members.project_id = sender_profiles.project_id
        AND project_members.user_id = auth.uid()
    )
  );

CREATE POLICY "Owners and editors can manage sender profiles"
  ON sender_profiles FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM project_members
      WHERE project_members.project_id = sender_profiles.project_id
        AND project_members.user_id = auth.uid()
        AND project_members.role IN ('owner', 'editor')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM project_members
      WHERE project_members.project_id = sender_profiles.project_id
        AND project_members.user_id = auth.uid()
        AND project_members.role IN ('owner', 'editor')
    )
  );
